---
functional:
  - Пользователь может зарегистрироваться и авторизоваться
  - Пользователь может начать игру против другого игрока
  - Пользователь может сыграть с ботом
  - Пользователь может пригласить друга по ссылке для игры
  - Пользователь может выбирать задачу по уровню сложности
  - Пользователь может решать задачу в онлайн-редакторе с подсветкой синтаксиса
  - Пользователь может видеть в реальном времени, что пишет соперник
  - Пользователь может получать результат проверки своего решения автоматически
  - Пользователь может просматривать результаты завершённых игр
  - Пользователь может общаться в чате во время игры
  - Пользователь может просматривать таблицу лидеров и свой рейтинг
  - Пользователь может наблюдать за чужими играми (spectator mode)
  - Пользователь может переключать язык интерфейса (русский/английский)

non-functional:
  - Адаптивная верстка (мобильная версия)
  - Оптимизация скорости работы приложения
  - Совместимость с последними версиями браузеров
  - Возможность обработки большого количества трафика
  - Наличие логирования ошибок и событий
  - Поддержка локализации интерфейса
  - Наличие документации для пользователей и разработчиков
  - Поддержка API для интеграции с внешними сервисами
  - Возможность масштабирования и расширения функционала

implicit:
  - Удобство использования (интуитивно понятный интерфейс)
  - Безопасность и защита данных пользователя
  - Возможность восстановления пароля
  - Защита от мошенничества и читерства
  - Устойчивость к атакам (XSS, SQL injection, DDoS)
  - Сохранение истории игр и решений пользователей
  - Возможность восстановления данных из бэкапов
  - Плавные обновления сервиса без простоя
  - Поддержка актуального стека технологий
  - Поддержка open-source развития и вклада сообщества
