functional:
  - Пользователь может зарегистрироваться и авторизоваться
  - Пользователь может начать игру против другого игрока
  - Пользователь может сыграть с ботом
  - Пользователь может пригласить друга по ссылке для игры
  - Пользователь может выбирать задачу по уровню сложности
  - Пользователь может решать задачу в онлайн-редакторе с подсветкой синтаксиса
  - Пользователь может видеть в реальном времени, что пишет соперник
  - Пользователь может получать результат проверки своего решения автоматически
  - Пользователь может просматривать результаты завершённых игр
  - Пользователь может общаться в чате во время игры
  - Пользователь может просматривать таблицу лидеров и свой рейтинг
  - Пользователь может наблюдать за чужими играми (spectator mode)
  - Пользователь может переключать язык интерфейса (русский/английский)
  - Пользователь может создавать новую игру (Create game)
  - Пользователь может подключаться к существующей игре (Connect to game)
  - Пользователь может ожидать соперника в лобби
  - Игра отображается как доступная для подключения у других пользователей
  - После подключения второго игрока игра начинается автоматически
  - Игроки видят два редактора (свой и соперника)
  - В интерфейсе отображается таймер и задание
  - Игрок может проверять своё решение неограниченное количество раз (кнопка "Check")
  - Изменения кода соперника видны в реальном времени
  - Если один из игроков вылетает, второй может продолжать игру
  - Игрок может переподключиться к незавершённой игре
  - Игра завершается, когда один из игроков решает задачу верно
  - После завершения отображается победитель
  - Победитель может выйти из игры, при этом кнопка "Check" становится неактивной
  - Проигравший может остаться и доиграть или выйти

non-functional:
  - Адаптивная верстка (мобильная версия)
  - Оптимизация скорости работы приложения
  - Совместимость с последними версиями браузеров
  - Возможность обработки большого количества трафика
  - Наличие логирования ошибок и событий
  - Поддержка локализации интерфейса
  - Наличие документации для пользователей и разработчиков
  - Поддержка API для интеграции с внешними сервисами
  - Возможность масштабирования и расширения функционала
  - Стабильное соединение в реальном времени
  - Высокая доступность и отказоустойчивость игрового сервера
  - Асинхронная обработка данных для мгновенного обновления интерфейса
  - Минимальная задержка при обмене данными между игроками
  - Эффективное использование ресурсов при множестве активных игр
  - Поддержка плавного восстановления соединения при временных сбоях

implicit:
  - Удобство использования (интуитивно понятный интерфейс)
  - Безопасность и защита данных пользователя
  - Возможность восстановления пароля
  - Защита от мошенничества и читерства
  - Устойчивость к атакам (XSS, SQL injection, DDoS)
  - Сохранение истории игр и решений пользователей
  - Возможность восстановления данных из бэкапов
  - Плавные обновления сервиса без простоя
  - Поддержка актуального стека технологий
  - Поддержка open-source развития и вклада сообщества
  - Корректное завершение игр при нештатных ситуациях
  - Сохранение прогресса и состояния игры при временной потере соединения
  - Прозрачная и справедливая система подсчёта результатов
  - Минимизация ошибок при проверке решений
